before fix to broken autox after upgrading some libraries to 15.10

diff --git a/autox b/autox
--- a/autox
+++ b/autox
@@ -26,7 +26,7 @@
 #		 is used.
 #
 #         NOTES:alias(1)
-#					- more than one argument present AND...
+#					- more than qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqone argument present AND...
 # 					- the first argument is either '-p' or '--' THEN...
 #					- remove it from the argument list
 # 					otherwise:
@@ -62,7 +62,162 @@
 # comment out if you are not developing autox
 cd ${AX_BASE:-~}
 
-if [[ -r $AX_BASE/cache/usecache ]]; then
+ax.cache.create()
+{
+	while true; do
+		getopts rh AXOPT
+		case $AXOPT in
+			d)	DELETE_CACHE=1
+				echo "-- entering cache removal mode --"
+				;;
+			h)  echo -e "usage: $FUNCNAME [-d] [-h]\n\n\t-d\tremove cache instead\n\t-h\tthis help text\n\nUse this command to create the cache for fast startup mode. It will be evaluated each time startups are made and recreated if needed. To disable this feature, use this command with the -d switch to delete the cache, or remove the cache manually.\n\n"
+				return 1
+				;;
+			*) 	return 2
+				;;
+		esac
+		[[ $OERR == 1 ]] && break
+
+	done
+
+	#####################################################################################
+	# the following environmental items must be cached, they are listed by filename followed by
+	# a brief description:
+	# value.act
+	# - values (from 'set') includes functions and variables of all kinds
+	#   anything that can be viewed with 'declare'
+	# binding.act
+	# - bindings (from 'bind') what is viewed by typing 'bind -psvX'
+	#   note must be loaded with 'bind -f [fname]'
+	# alias.act
+	# - aliases that come from typing 'alias'
+	# completion.act
+	# - completions from typing 'complete'
+	# option.act
+	# - shell options from 'shopt {-p,-po}'
+	# hash.act
+	# - hash executable names (from using 'hash -l')
+	# trap.act
+	# - traps (by using trap -l)
+	# shasum.act
+	# - a SHA256SUM of all the files above that are created
+	#
+	# Files are first created then a shasum is created to identify them
+	# TODO: future versions may roll into single file, ie, an XML with CDATA
+	#       once this method is perfected! (it is to remain the core method!)
+	#####################################################################################
+
+	if [[ -r $AX_BASE/autox ]]; then
+		AXBM="pre"
+	else
+		declare -gx AX_BASE
+		AX_BASE=$(readlink -a "$(dirname "$BASH_SOURCE")")
+		AXBM="manually "
+
+	fi
+
+	echo "AutoX base path has been ${AXBM}configured for use in $(tput bold)$AX_BASE$(tput sgr0)"
+
+	if [[ ! -r $AX_BASE/autox ]]; then
+		echo "...but it isnt valid, Stop."
+		return 1
+	fi
+
+
+	AX_CACHE_SITE=$AX_BASE/cache/usecache
+	((DELETE_CACHE)) && echo "Removing cache site..." || echo "Creating cache site..."
+	if [[ -d $AX_CACHE_SITE ]]; then
+		echo "Do you want to remove the old cache? (no undo) [y/n]:"
+		while [[ $(choice -sn1; echo $REPLY) =~ ^[^yn]$ ]]; do
+
+			echo "Please press [y] or [n]"
+		done
+		if [[ $REPLY == n ]]; then
+			echo "Aborted."
+			return 1
+		fi
+		if ! rm -fr "$AX_CACHE_SITE"; then
+			echo "Can't remove old data, check permissions"
+			return 1
+		fi
+	fi
+	if ((DELETE_CACHE)); then
+		echo "All That Can Be Done Has Been Done."
+		return 0
+	fi
+
+	if ! mkdir -p "$AX_CACHE_SITE" || ! touch "$AX_CACHE_SITE/.site_validation"; then
+		echo "Failed to create/write-to new cache site, please check your permissions!"
+		echo "at: $AX_CACHE_SITE"
+		return 1
+	fi
+
+	############ CACHE GENERATOR CODE[0*] ################
+	# Req Globals (Name)	(Default)	(Purpose)			(Possible Value(s))
+	#
+	# AX_BASE 				*			Tells where to find your AX install, usually in /usr[/local]/share/ax (systemwide) or ~/.local/share/ax (useronly)
+	#                                   but can self-detect on the fly, if needed (not usually needed though!)
+	#
+	#
+	# Locals (Name)			(Default)	(Purpose)			(Possible Value(s))
+	#
+	# AX_CACHE_SHA_SIZE		512256		Checksum Algorithm 	1, 224, 256, 384, 512, 512224, or 512256
+	# PROCS					*			commands used to store each section, the 'shasum' entry should NOT be changed
+	# STEPS                 *           the ORDERED keylisting of PROCS, since ${!PROCS[@]} may not be guarenteed order**
+	# PERCENT               -1			Used to track progress of the loop
+	# STEP, LAST            -1,#STEPS   Loop counter and Fixed End-Of-Array Bound
+	# incrementer			*			Expression used to initialize the state for each loop's file, step, and progress
+	# _ax__generate_values  * 			Functional (python-like) generator that processes the keys defined in PROC (and is self-destructable)
+	#
+	# Local Types: All items are type 'int' (integer, -i) except the generator (function), PROCS (dictionary), STEPS (list)
+	#
+	# Notes[0*] All types are local, however, we must execute the resulting in a global fashion, for this reason the function generates the final output
+	#         	for the loader to run AFTER it exits
+	#	    *   Item default is too long to list here, see original source for values on github or in your static directory
+	#      **   In programming, all programmers must assume lists to be ordered and dictionaries to be randomly ordered if at all, this
+	#           is proven and documented to be true in many scripting languages such as perl, python, javascript, to name a few. We also
+	#           borrow terms from python: list actually is 'array' and dictionary is actually 'named array'
+	#			however even if named arrays are constant-ordered, the order could change between versions of bash or compiled copies for that
+	# 			matter. There is no guarentee in the documentation that states the order to be fixed always in any specific manner.
+	#    ***    Shasums are used here to verify if a part of the system is out of sync with another part. We check our signature against
+	#  			the last-modified-time from stat (or axstat if installed in lib, see AX_CACHE_SHA_STAT). If any modification times have
+	#			changed on ANY file, the cache must be rebuilt, unless a force is used in which case it always will get built.
+	#           Conversely, if the cache is to be ignored, then the cache will never be rebuilt. (SEE AX_CACHE_PROVISION_STATE=IGNORE|ALWAYS|NONE)
+
+
+	# note: using a generator-style implementation to save on execution code size
+
+	declare -i AX_CACHE_SHA_SIZE=512
+	function _ax__generate_values() { eval "${PROCS[${STEPS[$2]}]}" > "$1" &&	(($2==$3)) && unset -f $FUNCNAME; }
+	declare -A PROCS=( [value]='builtin declare'
+					   [binding]='builtin bind -psvX'
+					   [alias]='builtin alias -p'
+					   [completion]='builtin complete'
+					   [option]='shopt -p; shopt -po'
+					   [hash]='hash -l'
+					   [trap]='trap -l'
+					   [shasum]='shasum $AX_CACHE_SITE/!(shasum.act) -a $AX_CACHE_SHA_SIZE'
+					 )
+
+	declare -a STEPS=( value binding alias completion option hash trap shasum )
+	declare -i PERCENT=-1 STEP=-1 LAST=${#STEPS[@]}-1
+	declare incrementer='let STEP++ "PERCENT=STEP*100/LAST"; echo -e "\E8${STEPS[$STEP]}s... ($PERCENT% completed)\E[J"; STEPF="$AX_CACHE_SITE/${STEPS[$STEP]}.act"'
+	echo -e "Creating Cache...\E7"
+	while [[ $STEP < $LAST ]]; do
+		eval $incrementer
+		_ax__generate_values "$STEPF" $STEP $LAST
+	done
+
+
+}
+
+ax.updatecache()
+{
+	# checks the signature
+	true
+}
+
+if false && [[ -r $AX_BASE/cache/usecache ]]; then
 	AX_CACHE_SITE=$AX_BASE/cache/usecache
 	SHAPRINT_THIS="$(eval shasum `find -type f -not -iname 'shasumprint' -not -type l -iname '*[^~]' -printf '"'$PWD'/%P"\n'` | shasum)"
 	[[ -r $AX_BASE/shasumprint ]] && SHAPRINT_PREV="$(cat $AX_BASE/shasumprint)" || SHAPRINT_PREV=NONE
@@ -81,7 +236,7 @@ if [[ -r $AX_BASE/cache/usecache ]]; then
 		echo "want to enable cache support again!"
 	fi
 else
-	if [[ -z ${AX_ONE_TIME_MESSAGES[NOCACHE]} ]]; then	
+	if [[ -z ${AX_ONE_TIME_MESSAGES[NOCACHE]} ]]; then
 		declare -gA AX_ONE_TIME_MESSAGES
 		AX_ONE_TIME_MESSAGES[NOCACHE]=1
 		echo "hint: no cache available, use ax.cache.create if you want faster load times!"
@@ -115,7 +270,7 @@ else
 fi
 
 
-	
+
 [[ $(tty) != "" ]] && ax.usage() { R=$?;cat $BASH_SOURCE | grep -Po '(?<=USAGE:\s).*$'; return $R; } || ax.usage() { :; }
 [[ -w ~/tmp/autox-dbg-logme ]] && echo "$@ from $(declare -p BASH_SOURCE)" >> /tmp/autox-startups
 [[ ! $- =~ i ]] && { echo;echo "please use \". $BASH_SOURCE\" to run this script!!";ax.usage;sleep 2;exit 1; }
@@ -126,7 +281,7 @@ fi
 
 if [[ $AX_STARTUP_FILE_NAME == ~/.bash_completion ]] && [[ $# -eq 0 ]]; then
 	##DEV ONLY COMMENTED OUT (2 LINES)
-	##echo -ne "invoked from: "; caller	
+	##echo -ne "invoked from: "; caller
 	##echo "$(tput bold)[${BASH_SOURCE[@]}]"
 	true debug echo "Running in Drop-In Mode ($AX_STARTUP_FILE_NAME)$(tput sgr0)"
 	# set some defaults -- because we might have been picked up
@@ -279,7 +434,7 @@ gexport(){
 	fi
 }
 
-alias() 
+alias()
 {
 	# prevents scripts from declaring permanant aliases
 	declare -gi AX_ALIAS_CALLS
@@ -321,9 +476,9 @@ alias()
 					echo "no alias, $1, defined global or local"
 					return 1
 				fi
-			fi					
-		fi		
-			
+			fi
+		fi
+
 	elif [[ $# -eq 0 ]]; then
 		builtin alias
 		return $?
@@ -454,8 +609,8 @@ ax.acquire()
 
 ax.load()
 {
-	
-	# SHIM echo "Entering ax.load"	
+
+	# SHIM echo "Entering ax.load"
 	ax.checkaliasdir || return 2
 	ALIAS_ITEMS=( $(grep -P '^\s*alias \S+=' $AX_BASE/alias/* --line-number | grep '^[^:]*(?=:1)' -P -o) )
 	ALIAS_CACHE=$(mktemp)
@@ -465,18 +620,18 @@ ax.load()
 	# SHIM	echo "Evaluating..."
 		source $ALIAS_CACHE
 	# SHIM	echo "Cleaning up..."
-		rm $ALIAS_CACHE	
+		rm $ALIAS_CACHE
 	else
 		echo "Warning: no aliases have been defined in the autox install of $AX_BASE"
 	fi
-		
+
 	#for i in $AX_BASE/alias/*; do
 	#	if grep -Pq '^alias\s+\S+=\S+' "$i"; then
 	#		tmploc=$(mktemp)
 	#		# optimize out the trivial call to alias()
 	#		cat "$i" | sed 's/^\s*alias/builtin alias/g' >> "$tmploc";
 	#		echo "load $i"
-	#		source $i; 
+	#		source $i;
 	#	else
 	#		ax.echo "skipping $i, does not appear to be an alias file..."
 	#	fi
@@ -532,10 +687,10 @@ ax.config() {
 		if [[ ${CONFIG_CACHE[$*]} ]]; then
 			RETV=${CONFIG_CACHE[$*]}
 			CACHELOAD=1
-		fi	
+		fi
 	fi
 	declare -gix ax_config_error=0
-	
+
 	if [[ -v RETV ]] || [[ -r $AX_BASE/config/autoxrc ]]; then
 	# config file read ok
 		if [[ -v RETV ]] || RETV=`grep "(?<=^${*}=).*$" -Po $AX_BASE/config/autoxrc`; then
@@ -551,7 +706,7 @@ ax.config() {
 				echo $RETV
 				return 1
 			fi
-		else			
+		else
 			CONFIG_CACHE[$*]="1"
 			ax_config_error=1
 			return 1
@@ -672,6 +827,8 @@ ax.helperalias() { # [alias helper (reserved for internal use) ]
 # hardwire a unique session id
 if [[ ! -v AX_SESSION_ID ]] && [[ -d $AX_BASE ]] && [[ -r $AX_BASE/autox ]]; then
 	AX_SESSION_ID_PREFIX="$USER:$GROUP:"
+	if [[ $AX_SESSION_ID_PREFIX == "$USER:$GROUP" ]]; then
+		AX_SESSION_ID=${AX_SESSION_ID_PREFIX}_0${RANDOM: 0: 5}
 fi
 
 # hardwire $TTY to $(tty) for this session
